name: example-ci-test
on:
  push:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17" # The Go version to download (if necessary) and use.

      - name: check linting
        run: golint .

      - name: test application
        run: go test ./tests
