name: example-ci-test
on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: setup go
      - uses: actions/setup-go@v2
      with:
        go-version: '1.17' # The Go version to download (if necessary) and use.

      - name: check linting
        run: make lint

      - name: test application
        run: make test