name: Example-CI Github Actions
on:
  push:
    branches: [ main ]
jobs:
   lint:
    runs-on: ubuntu-latest
    steps:
      - name: check linting
        run: make lint
    test:
      runs-on: ubuntu-latest
      steps:
        - name: test application
          run: make test